### ISSUE TITLE
Capture originator activation metrics

### ISSUE THREAD

**Issue by selfxp** [adobe-apiplatform/openwhisk-user-events#24]
### Definition
In the `Activation` message there are two namespaces defined:
* One is the `client`'s namespace found in the `namespace` fields
* The other one is the `executor`'s namespace, found in the `body.namespace`* field. 
As it can be seen in this example: 
```
{
  "body": {
    "statusCode": 0,
    "duration": 3,
    "name": "whisk.system/invokerHealthTestAction0",
    "waitTime": 583915671,
    "conductor": false,
    "kind": "nodejs:6",
    "initTime": 0,
    "memory": 256,
    "causedBy": false
  },
  "eventType": "Activation",
  "source": "invoker0",
  "subject": "demo",
  "timestamp": 1524476122676,
  "userId": "d0888ad5-5a92-435e-888a-d55a92935e54",
  "namespace": "demo"
}
```
In the current version of the `user-events` we're only tracking the namespace where the activation is being executed, but not who initiated it. 
### Proposal 
Track both namespaces with the same set of metrics. Increment `total` for `whisk.system` and `demo` namespace labels: 
```
openwhisk_action_activations_total{namespace="whisk.system"}
openwhisk_action_activations_total{namespace="demo"}
```
`Note:` In case the action has been executed from the same namespace (`namespace` == `body.namespace`*), we should only count the execution once.

> \* By `body.namespace` we mean the namespace part of the `body.name` field value.
Example: `whisk.system/invokerHealthTestAction0` -> `whisk.system`

WDYT @chetanmeh

**Comment by chetanmeh** [comment]
That should be ok to start with. 

1. We should have a label to distinguish between the 2 like `initiator="true"`
2. We should then have a separate count for overall aggregate across the system or use the above label to filter out.

**Comment by selfxp** [comment]
2. I'm wondering if not `openwhisk_action_activations_total{initiator="false"}` is the actual overall aggregate in this case, as it will get incremented with every `Activation` event.

**Comment by chetanmeh** [comment]
We can use that ... just that it would have the computation overhead. If we keep a dedicate metric for overall aggregation then reading it would be faster and there would be minimal storage overhead

**Comment by selfxp** [comment]
Given that fact that there is no way to make a correlation between the `initiator` and `executor` I suggest solving this by adding another tag inside the existing metric, this would look like this if namespaces are different:
```
openwhisk_action_activations_total{namespace="whisk.system", initiator="demo"}
```
and this if they are the same: 
```
openwhisk_action_activations_total{namespace="guest", initiator="guest"}
```
This would allow us to make correlations between the two, for example answer the question:
`How many external invocations a namespace has?`. WDYT @chetanmeh ?

**Comment by chetanmeh** [comment]
👍 makes sense to capture it as another tag in our existing metrics.
