### ISSUE TITLE
No precision with second duration values

### ISSUE THREAD

**Issue by selfxp** [adobe-apiplatform/openwhisk-user-events#40]
All durations sent to Prometheus are rounded to integer values [here](https://github.com/adobe-apiplatform/openwhisk-user-events/blob/master/src/main/scala/com/adobe/api/platform/runtime/metrics/PrometheusRecorder.scala#L99).
We should transform to a double value: e.g.`100ms` -> `0.1sec`

**Comment by chetanmeh** [comment]
Good find. Should have used doubled here!
